# Generated by Django 5.2.15 on 2026-07-06 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        ("projects", "0001_initial"),
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("HARD", "Hard Rule (자동 무시 불가)"),
                            ("RECOMMENDATION", "Recommendation Rule"),
                        ],
                        default="RECOMMENDATION",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("conditions_json", models.JSONField(blank=True, default=dict)),
                ("effects_json", models.JSONField(blank=True, default=list)),
                ("explanation_template", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "정보"),
                            ("WARNING", "경고"),
                            ("ERROR", "오류"),
                            ("CRITICAL", "치명적"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("applicable_scope", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-priority", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"), name="uniq_rule_code_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DesignDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("decision_type", models.CharField(max_length=100)),
                ("subject_type", models.CharField(blank=True, max_length=100)),
                ("subject_id", models.CharField(blank=True, max_length=100)),
                ("decision_value_json", models.JSONField()),
                ("reason", models.TextField()),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "치명적"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("approval_required", models.BooleanField(default=False)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성 중"),
                            ("IN_REVIEW", "검토 중"),
                            ("APPROVED", "승인됨"),
                            ("REJECTED", "거절됨"),
                            ("SUPERSEDED", "대체됨"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "input_facts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="design_decisions",
                        to="requirements.projectfact",
                    ),
                ),
                (
                    "knowledge_items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="design_decisions",
                        to="knowledge.knowledgeitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_decisions",
                        to="projects.project",
                    ),
                ),
                (
                    "rules",
                    models.ManyToManyField(
                        blank=True, related_name="design_decisions", to="design.rule"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "decision_type"],
                        name="design_desi_project_f95a93_idx",
                    )
                ],
            },
        ),
    ]
