# Generated by Django 5.2.15 on 2026-07-07 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="designdecision",
            name="generated_by_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_decisions",
                to="design.rule",
            ),
        ),
        migrations.AddField(
            model_name="designdecision",
            name="overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="designdecision",
            name="override_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
