# Generated by Django 5.2.15 on 2026-07-07 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "정보"),
                            ("WARNING", "경고"),
                            ("ERROR", "오류"),
                            ("CRITICAL", "치명적"),
                        ],
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("related_objects", models.JSONField(blank=True, default=list)),
                ("recommended_action", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "미해결"),
                            ("ACKNOWLEDGED", "확인됨"),
                            ("RESOLVED", "해결됨"),
                            ("WAIVED", "예외 승인"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_findings",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "code"],
                "indexes": [
                    models.Index(
                        fields=["project", "severity"],
                        name="validation__project_17dc01_idx",
                    )
                ],
            },
        ),
    ]
