# Generated by Django 5.2.15 on 2026-07-07 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[("FAT", "FAT"), ("SAT", "SAT")], max_length=3
                    ),
                ),
                ("test_id", models.CharField(max_length=50)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("precondition", models.TextField(blank=True)),
                ("procedure", models.TextField(blank=True)),
                ("expected_result", models.TextField(blank=True)),
                ("actual_result", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_RUN", "미실행"),
                            ("PASS", "합격"),
                            ("FAIL", "불합격"),
                            ("BLOCKED", "보류"),
                        ],
                        default="NOT_RUN",
                        max_length=10,
                    ),
                ),
                ("evidence", models.CharField(blank=True, max_length=255)),
                ("tester", models.CharField(blank=True, max_length=100)),
                ("reviewer", models.CharField(blank=True, max_length=100)),
                ("source_type", models.CharField(blank=True, max_length=30)),
                ("source_ref", models.CharField(blank=True, max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "test_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "phase", "test_id"),
                        name="uniq_test_per_project_phase",
                    )
                ],
            },
        ),
    ]
