"""초기 질문 데이터 50개 (PRD §28 Phase 1 목표, D5: 식품+수처리 우선).

⚠️ Safety 관련 질문(SAFETY/INTERLOCK)은 자동화 전문가 검토 후 확정한다 (D6).
answer_schema를 생략하면 question_type별 기본 스키마가 적용된다.
"""

DEFAULT_SCHEMAS = {
    "TEXT": {"type": "string", "minLength": 1},
    "YES_NO": {"type": ["boolean", "string"]},
    "SINGLE_CHOICE": {"type": "string"},
    "MULTI_CHOICE": {"type": "array", "items": {"type": "string"}},
    "INTEGER": {"type": "integer", "minimum": 0},
    "DECIMAL": {"type": "number"},
    "RANGE": {"type": "object", "required": ["min", "max"]},
    "UNIT_VALUE": {"type": "object", "required": ["value", "unit"]},
    "DEVICE_LIST": {"type": "array", "items": {"type": "string"}, "minItems": 1},
    "TABLE": {"type": "array"},
    "FILE_UPLOAD": {"type": "string"},
    "CONFIRMATION": {"type": ["boolean", "string"]},
}

# (선택지가 있는 질문은 "options": [(value, label)] 로 표기)
QUESTIONS = [
    # ── 회사/업종/공정 ──────────────────────────────────
    {
        "code": "Q-IND-001",
        "category": "INDUSTRY",
        "question_type": "SINGLE_CHOICE",
        "text": "어떤 업종의 현장입니까?",
        "criticality": "CRITICAL",
        "priority": 100,
        "unlocks_facts": ["INDUSTRY"],
        "unlocks_decisions": ["KNOWLEDGE_SCOPE"],
        "options": [
            ("식품", "식품"),
            ("수처리", "수처리"),
            ("일반 제조", "일반 제조"),
            ("물류", "물류"),
            ("스마트팜", "스마트팜"),
        ],
    },
    {
        "code": "Q-PROC-001",
        "category": "PROCESS",
        "question_type": "MULTI_CHOICE",
        "text": "자동화 대상 공정을 모두 선택해 주세요.",
        "criticality": "CRITICAL",
        "priority": 95,
        "unlocks_facts": ["PROCESSES"],
        "unlocks_decisions": ["PROCESS_MODEL"],
        "options": [
            ("Tank Storage", "탱크 저장"),
            ("Liquid Transfer", "액체 이송"),
            ("Mixing", "교반/혼합"),
            ("Heating", "가열"),
            ("Cooling", "냉각"),
            ("Conveyor Transfer", "컨베이어 이송"),
            ("Packaging", "포장"),
            ("Inspection", "검사"),
            ("Batch Process", "배치 공정"),
            ("Continuous Process", "연속 공정"),
        ],
    },
    {
        "code": "Q-PROC-002",
        "category": "PROCESS",
        "question_type": "SINGLE_CHOICE",
        "text": "공정은 배치(회분식)입니까, 연속식입니까?",
        "criticality": "HIGH",
        "priority": 60,
        "unlocks_facts": ["PROCESS_MODE"],
        "options": [("BATCH", "배치"), ("CONTINUOUS", "연속"), ("MIXED", "혼합")],
    },
    {
        "code": "Q-COMP-001",
        "category": "COMPANY",
        "question_type": "TEXT",
        "text": "회사와 현장(공장) 위치를 알려주세요.",
        "criticality": "LOW",
        "priority": 10,
        "unlocks_facts": ["COMPANY_PROFILE"],
    },
    {
        "code": "Q-PROC-003",
        "category": "PROCESS",
        "question_type": "MULTI_CHOICE",
        "text": "수처리 계통에서 자동화 대상 단계를 선택해 주세요.",
        "criticality": "HIGH",
        "priority": 55,
        "applicable_industries": ["수처리"],
        "unlocks_facts": ["WATER_TREATMENT_STAGES"],
        "unlocks_decisions": ["PROCESS_MODEL"],
        "options": [
            ("INTAKE", "취수/원수"),
            ("COAGULATION", "약품 투입/응집"),
            ("SEDIMENTATION", "침전"),
            ("FILTRATION", "여과"),
            ("DISINFECTION", "소독"),
            ("DISCHARGE", "방류/송수"),
            ("SLUDGE", "슬러지 처리"),
        ],
    },
    # ── 생산 ───────────────────────────────────────────
    {
        "code": "Q-PROD-001",
        "category": "PRODUCTION",
        "question_type": "UNIT_VALUE",
        "text": "목표 생산량(또는 처리량)은 얼마입니까?",
        "help_text": "예: 시간당 500L, 일 10톤 등 단위와 함께 입력",
        "criticality": "MEDIUM",
        "priority": 40,
        "unlocks_facts": ["PRODUCTION_TARGET"],
    },
    {
        "code": "Q-PROD-002",
        "category": "PRODUCTION",
        "question_type": "SINGLE_CHOICE",
        "text": "가동 형태는 어떻게 됩니까?",
        "criticality": "LOW",
        "priority": 20,
        "unlocks_facts": ["OPERATION_PATTERN"],
        "options": [("1SHIFT", "주간 1교대"), ("2SHIFT", "2교대"), ("3SHIFT", "3교대/24시간")],
    },
    # ── 설비 ───────────────────────────────────────────
    {
        "code": "Q-DEV-001",
        "category": "DEVICE",
        "question_type": "DEVICE_LIST",
        "text": "제어 대상 설비를 모두 알려주세요.",
        "help_text": "예: 모터, 펌프, 밸브, 탱크, 컨베이어, 히터, 팬, 인버터 등",
        "criticality": "CRITICAL",
        "priority": 90,
        "unlocks_facts": ["DEVICE_LIST"],
        "unlocks_decisions": ["IO_ESTIMATION", "PLC_SIZING"],
    },
    {
        "code": "Q-DEV-002",
        "category": "DEVICE",
        "question_type": "INTEGER",
        "text": "탱크는 몇 개입니까?",
        "criticality": "HIGH",
        "priority": 55,
        "required_conditions": {"in": ["Tank Storage", {"var": "PROCESSES"}]},
        "unlocks_facts": ["TANK_COUNT"],
    },
    {
        "code": "Q-DEV-003",
        "category": "DEVICE",
        "question_type": "INTEGER",
        "text": "펌프(또는 모터)는 몇 대입니까?",
        "criticality": "MEDIUM",
        "priority": 45,
        "unlocks_facts": ["PUMP_COUNT"],
    },
    {
        "code": "Q-DEV-004",
        "category": "DEVICE",
        "question_type": "YES_NO",
        "text": "속도 제어가 필요한 설비(인버터 적용 대상)가 있습니까?",
        "criticality": "HIGH",
        "priority": 50,
        "unlocks_facts": ["INVERTER_USED"],
        "unlocks_decisions": ["COMMUNICATION_DESIGN"],
    },
    {
        "code": "Q-DEV-005",
        "category": "DEVICE",
        "question_type": "YES_NO",
        "text": "실린더 등 공압 구동 설비가 있습니까?",
        "criticality": "MEDIUM",
        "priority": 35,
        "unlocks_facts": ["PNEUMATIC_USED"],
    },
    {
        "code": "Q-DEV-006",
        "category": "DEVICE",
        "question_type": "INTEGER",
        "text": "자동 개폐가 필요한 밸브는 몇 개입니까?",
        "criticality": "MEDIUM",
        "priority": 40,
        "unlocks_facts": ["AUTO_VALVE_COUNT"],
    },
    # ── 물질/위생 ──────────────────────────────────────
    {
        "code": "Q-MAT-001",
        "category": "MATERIAL",
        "question_type": "TEXT",
        "text": "취급하는 물질(원료/제품)은 무엇입니까?",
        "criticality": "HIGH",
        "priority": 50,
        "unlocks_facts": ["MATERIALS"],
    },
    {
        "code": "Q-MAT-002",
        "category": "MATERIAL",
        "question_type": "YES_NO",
        "text": "식품 접촉부의 위생 등급(위생 배관, 위생 센서)이 요구됩니까?",
        "criticality": "HIGH",
        "priority": 45,
        "applicable_industries": ["식품"],
        "unlocks_facts": ["SANITARY_REQUIRED"],
    },
    {
        "code": "Q-MAT-003",
        "category": "MATERIAL",
        "question_type": "YES_NO",
        "text": "부식성 물질(약품 등)을 취급합니까?",
        "criticality": "HIGH",
        "priority": 45,
        "applicable_industries": ["수처리", "식품", "일반 제조"],
        "unlocks_facts": ["CORROSIVE_MATERIAL"],
    },
    # ── 센서/계측 ──────────────────────────────────────
    {
        "code": "Q-SEN-001",
        "category": "SENSOR",
        "question_type": "MULTI_CHOICE",
        "text": "측정이 필요한 항목을 모두 선택해 주세요.",
        "criticality": "CRITICAL",
        "priority": 85,
        "unlocks_facts": ["MEASUREMENT_REQUIREMENTS"],
        "unlocks_decisions": ["SENSOR_DESIGN"],
        "options": [
            ("LEVEL", "레벨"),
            ("TEMPERATURE", "온도"),
            ("PRESSURE", "압력"),
            ("FLOW", "유량"),
            ("PH", "pH/수질"),
            ("WEIGHT", "중량"),
            ("POSITION", "위치/근접"),
            ("VIBRATION", "진동"),
            ("CURRENT", "전류"),
        ],
    },
    {
        "code": "Q-SEN-002",
        "category": "SENSOR",
        "question_type": "YES_NO",
        "text": "레벨은 연속 측정(현재 수위 %)이 필요합니까? 아니면 상/하한 감지만으로 충분합니까?",
        "help_text": "예=연속 측정 필요, 아니오=상/하한 스위치로 충분",
        "criticality": "HIGH",
        "priority": 55,
        "required_conditions": {"in": ["LEVEL", {"var": "MEASUREMENT_REQUIREMENTS"}]},
        "unlocks_facts": ["CONTINUOUS_LEVEL_REQUIRED"],
        "unlocks_decisions": ["SENSOR_DESIGN"],
    },
    {
        "code": "Q-SEN-003",
        "category": "SENSOR",
        "question_type": "TEXT",
        "text": "탱크의 사용 환경을 설명해 주세요. (온도, 증기, 거품, 교반 여부 등)",
        "criticality": "HIGH",
        "priority": 50,
        "required_conditions": {">": [{"var": "TANK_COUNT"}, 0]},
        "unlocks_facts": ["TANK_ENVIRONMENT"],
        "unlocks_decisions": ["SENSOR_DESIGN"],
        "risk_detection_tags": ["STEAM", "HIGH_TEMPERATURE"],
    },
    {
        "code": "Q-SEN-004",
        "category": "SENSOR",
        "question_type": "UNIT_VALUE",
        "text": "공정의 최대 운전 온도는 얼마입니까?",
        "criticality": "MEDIUM",
        "priority": 40,
        "unlocks_facts": ["MAX_TEMPERATURE_APPROX"],
    },
    {
        "code": "Q-SEN-005",
        "category": "SENSOR",
        "question_type": "UNIT_VALUE",
        "text": "공정의 최대 운전 압력은 얼마입니까?",
        "criticality": "MEDIUM",
        "priority": 40,
        "unlocks_facts": ["MAX_PRESSURE"],
    },
    {
        "code": "Q-SEN-006",
        "category": "SENSOR",
        "question_type": "YES_NO",
        "text": "계량(중량 기반 배합)이 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 35,
        "applicable_industries": ["식품", "일반 제조"],
        "unlocks_facts": ["WEIGHING_REQUIRED"],
    },
    {
        "code": "Q-SEN-007",
        "category": "SENSOR",
        "question_type": "YES_NO",
        "text": "pH/잔류염소 등 수질 항목의 자동 제어(약품 주입 연동)가 필요합니까?",
        "criticality": "HIGH",
        "priority": 50,
        "applicable_industries": ["수처리"],
        "required_conditions": {"in": ["PH", {"var": "MEASUREMENT_REQUIREMENTS"}]},
        "unlocks_facts": ["PH_CONTROL_REQUIRED"],
        "unlocks_decisions": ["SENSOR_DESIGN"],
    },
    # ── 품질 ───────────────────────────────────────────
    {
        "code": "Q-QUA-001",
        "category": "QUALITY",
        "question_type": "YES_NO",
        "text": "품질 데이터(온도 이력, 배합 기록 등)의 기록/보관이 필요합니까?",
        "criticality": "HIGH",
        "priority": 45,
        "unlocks_facts": ["QUALITY_LOGGING_REQUIRED"],
        "unlocks_decisions": ["HISTORIAN_DESIGN"],
    },
    # ── 안전 (⚠️ 전문가 검토 필수) ──────────────────────
    {
        "code": "Q-SAF-001",
        "category": "SAFETY",
        "question_type": "TEXT",
        "text": "현장의 주요 위험 요소를 알려주세요. (고온, 고압, 회전체, 낙하물, 약품 등)",
        "criticality": "CRITICAL",
        "priority": 95,
        "unlocks_facts": ["SAFETY_REQUIREMENTS"],
        "unlocks_decisions": ["INTERLOCK_DESIGN", "ALARM_DESIGN"],
        "risk_detection_tags": ["SAFETY"],
    },
    {
        "code": "Q-SAF-002",
        "category": "SAFETY",
        "question_type": "YES_NO",
        "text": "비상정지(E-Stop) 버튼이 필요한 구역이 있습니까?",
        "criticality": "CRITICAL",
        "priority": 90,
        "unlocks_facts": ["ESTOP_REQUIRED"],
        "unlocks_decisions": ["SAFETY_IO_SIZING"],
        "risk_detection_tags": ["SAFETY"],
    },
    {
        "code": "Q-SAF-003",
        "category": "SAFETY",
        "question_type": "YES_NO",
        "text": "인터록을 일시 해제(바이패스)해야 하는 운전 상황이 있습니까?",
        "help_text": "있다면 권한/기록 정책이 함께 설계됩니다.",
        "criticality": "HIGH",
        "priority": 55,
        "unlocks_facts": ["BYPASS_POLICY_REQUIRED"],
        "risk_detection_tags": ["SAFETY"],
    },
    {
        "code": "Q-SAF-004",
        "category": "SAFETY",
        "question_type": "YES_NO",
        "text": "적용해야 하는 안전 규격/인증(KOSHA, CE 등)이 있습니까?",
        "criticality": "HIGH",
        "priority": 50,
        "unlocks_facts": ["SAFETY_STANDARD_REQUIRED"],
        "risk_detection_tags": ["SAFETY"],
    },
    # ── 환경 ───────────────────────────────────────────
    {
        "code": "Q-ENV-001",
        "category": "ENVIRONMENT",
        "question_type": "SINGLE_CHOICE",
        "text": "설비 설치 환경은 어디입니까?",
        "criticality": "MEDIUM",
        "priority": 35,
        "unlocks_facts": ["INSTALL_ENVIRONMENT"],
        "options": [("INDOOR", "옥내"), ("OUTDOOR", "옥외"), ("MIXED", "혼합")],
    },
    {
        "code": "Q-ENV-002",
        "category": "ENVIRONMENT",
        "question_type": "YES_NO",
        "text": "세척(CIP/워시다운)이 있습니까?",
        "criticality": "HIGH",
        "priority": 50,
        "applicable_industries": ["식품", "수처리"],
        "unlocks_facts": ["CIP_REQUIRED"],
        "risk_detection_tags": ["STEAM", "WATER_INGRESS"],
    },
    {
        "code": "Q-ENV-003",
        "category": "ENVIRONMENT",
        "question_type": "YES_NO",
        "text": "방폭 지역(위험 물질 분위기)이 있습니까?",
        "criticality": "HIGH",
        "priority": 55,
        "unlocks_facts": ["HAZARDOUS_AREA"],
        "risk_detection_tags": ["SAFETY", "EXPLOSION"],
    },
    {
        "code": "Q-ENV-004",
        "category": "ENVIRONMENT",
        "question_type": "YES_NO",
        "text": "저온(냉동/냉장) 환경이 있습니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "applicable_industries": ["식품", "물류"],
        "unlocks_facts": ["COLD_ENVIRONMENT"],
    },
    {
        "code": "Q-ENV-005",
        "category": "ENVIRONMENT",
        "question_type": "SINGLE_CHOICE",
        "text": "판넬에 공급 가능한 전원 사양은 무엇입니까?",
        "criticality": "MEDIUM",
        "priority": 35,
        "unlocks_facts": ["POWER_SPEC"],
        "options": [
            ("AC220", "AC 220V 단상"),
            ("AC380", "AC 380V 3상"),
            ("BOTH", "둘 다 가능"),
            ("UNKNOWN", "모름"),
        ],
    },
    # ── 유지보수 ────────────────────────────────────────
    {
        "code": "Q-MNT-001",
        "category": "MAINTENANCE",
        "question_type": "SINGLE_CHOICE",
        "text": "현장의 유지보수 인력 수준은 어떻습니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "unlocks_facts": ["MAINTENANCE_CAPABILITY"],
        "unlocks_decisions": ["PLC_SIZING"],
        "options": [
            ("NONE", "전담 인력 없음"),
            ("BASIC", "전기 기초 가능"),
            ("PLC", "PLC 유지보수 가능"),
        ],
    },
    {
        "code": "Q-MNT-002",
        "category": "MAINTENANCE",
        "question_type": "YES_NO",
        "text": "예비품(스페어 파트) 보유 정책이 있습니까?",
        "criticality": "LOW",
        "priority": 15,
        "unlocks_facts": ["SPARE_PARTS_POLICY"],
    },
    # ── 네트워크/통신 ───────────────────────────────────
    {
        "code": "Q-NET-001",
        "category": "NETWORK",
        "question_type": "YES_NO",
        "text": "공장에 기존 산업용 네트워크(이더넷 등)가 구축되어 있습니까?",
        "criticality": "MEDIUM",
        "priority": 35,
        "unlocks_facts": ["EXISTING_NETWORK"],
    },
    {
        "code": "Q-NET-002",
        "category": "NETWORK",
        "question_type": "YES_NO",
        "text": "사무실/외부에서의 원격 모니터링이 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 35,
        "unlocks_facts": ["REMOTE_MONITORING_REQUIRED"],
        "unlocks_decisions": ["COMMUNICATION_DESIGN"],
    },
    {
        "code": "Q-COM-001",
        "category": "COMMUNICATION",
        "question_type": "MULTI_CHOICE",
        "text": "PLC와 통신으로 연동할 장치를 선택해 주세요.",
        "criticality": "HIGH",
        "priority": 50,
        "unlocks_facts": ["COMM_TARGETS"],
        "unlocks_decisions": ["COMMUNICATION_DESIGN"],
        "options": [
            ("INVERTER", "인버터"),
            ("SERVO", "서보"),
            ("METER", "전력/유량계"),
            ("BARCODE", "바코드/비전"),
            ("SCALE", "전자저울"),
            ("ROBOT", "로봇"),
            ("NONE", "없음/모름"),
        ],
    },
    {
        "code": "Q-COM-002",
        "category": "COMMUNICATION",
        "question_type": "SINGLE_CHOICE",
        "text": "선호하거나 표준으로 쓰는 통신 프로토콜이 있습니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "unlocks_facts": ["PREFERRED_PROTOCOL"],
        "options": [
            ("NONE", "없음/모름"),
            ("MODBUS", "Modbus"),
            ("ETHERNET_IP", "EtherNet/IP"),
            ("PROFINET", "PROFINET"),
            ("CC_LINK", "CC-Link"),
            ("OPC_UA", "OPC UA"),
        ],
    },
    # ── PLC ────────────────────────────────────────────
    {
        "code": "Q-PLC-001",
        "category": "PLC",
        "question_type": "SINGLE_CHOICE",
        "text": "기존에 사용 중이거나 선호하는 PLC 제조사가 있습니까?",
        "criticality": "HIGH",
        "priority": 55,
        "unlocks_facts": ["EXISTING_PLC_VENDOR"],
        "unlocks_decisions": ["PLC_SIZING"],
        "options": [
            ("NONE", "없음/무관"),
            ("LS", "LS ELECTRIC"),
            ("SIEMENS", "Siemens"),
            ("MITSUBISHI", "Mitsubishi"),
            ("AB", "Allen-Bradley"),
            ("OTHER", "기타"),
        ],
    },
    {
        "code": "Q-PLC-002",
        "category": "PLC",
        "question_type": "SINGLE_CHOICE",
        "text": "운전 방식은 어떻게 하시겠습니까?",
        "criticality": "CRITICAL",
        "priority": 80,
        "unlocks_facts": ["CONTROL_MODE"],
        "unlocks_decisions": ["PLC_SIZING", "SEQUENCE_DESIGN", "HMI_DESIGN"],
        "options": [
            ("AUTO", "전자동 (시퀀스 운전)"),
            ("SEMI", "반자동 (수동+자동 혼합)"),
            ("MANUAL", "수동 중심"),
        ],
    },
    {
        "code": "Q-PLC-003",
        "category": "PLC",
        "question_type": "YES_NO",
        "text": "제어기 이중화(Redundancy)가 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "unlocks_facts": ["REDUNDANCY_REQUIRED"],
        "unlocks_decisions": ["PLC_SIZING"],
    },
    {
        "code": "Q-PLC-004",
        "category": "PLC",
        "question_type": "YES_NO",
        "text": "향후 라인 증설/확장 계획이 있습니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "unlocks_facts": ["FUTURE_EXPANSION"],
        "unlocks_decisions": ["PLC_SIZING"],
    },
    # ── HMI/SCADA/Historian/MES ─────────────────────────
    {
        "code": "Q-HMI-001",
        "category": "HMI",
        "question_type": "YES_NO",
        "text": "현장 운전용 HMI(터치패널)가 필요합니까?",
        "criticality": "CRITICAL",
        "priority": 75,
        "unlocks_facts": ["HMI_REQUIRED"],
        "unlocks_decisions": ["HMI_DESIGN"],
    },
    {
        "code": "Q-HMI-002",
        "category": "HMI",
        "question_type": "INTEGER",
        "text": "HMI를 사용할 운전 인원은 몇 명입니까?",
        "criticality": "LOW",
        "priority": 15,
        "required_conditions": {"==": [{"var": "HMI_REQUIRED"}, True]},
        "unlocks_facts": ["HMI_USER_COUNT"],
    },
    {
        "code": "Q-HMI-003",
        "category": "HMI",
        "question_type": "YES_NO",
        "text": "온도/수위 등의 트렌드(그래프) 화면이 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "required_conditions": {"==": [{"var": "HMI_REQUIRED"}, True]},
        "unlocks_facts": ["TREND_REQUIRED"],
        "unlocks_decisions": ["HMI_DESIGN"],
    },
    {
        "code": "Q-HMI-004",
        "category": "HMI",
        "question_type": "YES_NO",
        "text": "제품별 배합/운전 조건(레시피) 관리가 필요합니까?",
        "criticality": "HIGH",
        "priority": 45,
        "applicable_industries": ["식품", "일반 제조"],
        "required_conditions": {"==": [{"var": "HMI_REQUIRED"}, True]},
        "unlocks_facts": ["RECIPE_REQUIRED"],
        "unlocks_decisions": ["HMI_DESIGN"],
    },
    {
        "code": "Q-HMI-005",
        "category": "HMI",
        "question_type": "YES_NO",
        "text": "운전자/관리자 등 사용자 권한 구분이 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "required_conditions": {"==": [{"var": "HMI_REQUIRED"}, True]},
        "unlocks_facts": ["USER_ACCESS_LEVELS"],
        "unlocks_decisions": ["HMI_DESIGN"],
    },
    {
        "code": "Q-SCA-001",
        "category": "SCADA",
        "question_type": "YES_NO",
        "text": "중앙 감시실(SCADA)에서의 통합 감시가 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 35,
        "unlocks_facts": ["SCADA_REQUIRED"],
        "unlocks_decisions": ["COMMUNICATION_DESIGN"],
    },
    {
        "code": "Q-HIS-001",
        "category": "HISTORIAN",
        "question_type": "YES_NO",
        "text": "운전 데이터의 장기 보관(수개월~수년)이 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "required_conditions": {
            "or": [
                {"==": [{"var": "QUALITY_LOGGING_REQUIRED"}, True]},
                {"==": [{"var": "SCADA_REQUIRED"}, True]},
            ]
        },
        "unlocks_facts": ["HISTORIAN_REQUIRED"],
    },
    {
        "code": "Q-MES-001",
        "category": "MES_ERP",
        "question_type": "YES_NO",
        "text": "MES/ERP 등 상위 시스템과의 연동이 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 30,
        "unlocks_facts": ["MES_INTEGRATION_REQUIRED"],
        "unlocks_decisions": ["COMMUNICATION_DESIGN"],
    },
    # ── 알람/인터록/시퀀스 ──────────────────────────────
    {
        "code": "Q-ALM-001",
        "category": "ALARM",
        "question_type": "YES_NO",
        "text": "알람 발생 시 현장 외 통보(경광등, 부저, 문자 등)가 필요합니까?",
        "criticality": "MEDIUM",
        "priority": 35,
        "unlocks_facts": ["ALARM_NOTIFICATION_REQUIRED"],
        "unlocks_decisions": ["ALARM_DESIGN"],
    },
    {
        "code": "Q-ALM-002",
        "category": "ALARM",
        "question_type": "TEXT",
        "text": "반드시 감시해야 하는 이상 상황(알람 항목)을 알려주세요.",
        "criticality": "HIGH",
        "priority": 45,
        "unlocks_facts": ["CRITICAL_ALARMS"],
        "unlocks_decisions": ["ALARM_DESIGN"],
    },
    {
        "code": "Q-ALM-003",
        "category": "ALARM",
        "question_type": "SINGLE_CHOICE",
        "text": "정전 후 복전 시 설비는 어떻게 동작해야 합니까?",
        "criticality": "HIGH",
        "priority": 55,
        "unlocks_facts": ["POWER_FAILURE_POLICY"],
        "unlocks_decisions": ["SEQUENCE_DESIGN", "INTERLOCK_DESIGN"],
        "risk_detection_tags": ["SAFETY"],
        "options": [
            ("STOP", "정지 유지 (수동 재기동)"),
            ("RESUME", "자동 재기동"),
            ("CONDITIONAL", "조건부 재기동"),
        ],
    },
    {
        "code": "Q-ILK-001",
        "category": "INTERLOCK",
        "question_type": "TEXT",
        "text": "설비 보호를 위해 반드시 지켜야 하는 조건이 있습니까? (예: 수위 낮으면 펌프 금지)",
        "criticality": "CRITICAL",
        "priority": 85,
        "unlocks_facts": ["INTERLOCK_REQUIREMENTS"],
        "unlocks_decisions": ["INTERLOCK_DESIGN"],
        "risk_detection_tags": ["SAFETY"],
    },
    {
        "code": "Q-SEQ-001",
        "category": "SEQUENCE",
        "question_type": "TEXT",
        "text": "자동 운전의 순서를 단계별로 설명해 주세요.",
        "criticality": "HIGH",
        "priority": 50,
        "required_conditions": {"in": [{"var": "CONTROL_MODE"}, ["AUTO", "SEMI"]]},
        "unlocks_facts": ["SEQUENCE_OUTLINE"],
        "unlocks_decisions": ["SEQUENCE_DESIGN"],
    },
    # ── FAT/SAT/납품 ────────────────────────────────────
    {
        "code": "Q-FAT-001",
        "category": "FAT",
        "question_type": "YES_NO",
        "text": "출하 전 공장 시험(FAT)에 고객 입회가 필요합니까?",
        "criticality": "LOW",
        "priority": 15,
        "unlocks_facts": ["FAT_WITNESS_REQUIRED"],
    },
    {
        "code": "Q-SAT-001",
        "category": "SAT",
        "question_type": "YES_NO",
        "text": "현장 설치 후 시운전(SAT) 지원이 필요합니까?",
        "criticality": "LOW",
        "priority": 15,
        "unlocks_facts": ["SAT_SUPPORT_REQUIRED"],
    },
    {
        "code": "Q-DEL-001",
        "category": "DELIVERY",
        "question_type": "MULTI_CHOICE",
        "text": "납품 시 필요한 문서를 선택해 주세요.",
        "criticality": "LOW",
        "priority": 15,
        "unlocks_facts": ["DELIVERY_DOCUMENTS"],
        "options": [
            ("IO_LIST", "I/O List"),
            ("WIRING", "결선도"),
            ("MANUAL", "운전 매뉴얼"),
            ("ALARM_LIST", "알람 리스트"),
            ("FAT_REPORT", "FAT 성적서"),
            ("SAT_REPORT", "SAT 성적서"),
        ],
    },
    {
        "code": "Q-DEL-002",
        "category": "DELIVERY",
        "question_type": "TEXT",
        "text": "희망 납기(완료 시점)는 언제입니까?",
        "criticality": "LOW",
        "priority": 10,
        "unlocks_facts": ["TARGET_DELIVERY_DATE"],
    },
]
