# Generated by Django 5.2.15 on 2026-07-07 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("REQUIREMENT_BASELINE", "요구사항 Baseline"),
                            ("SENSOR_DESIGN", "센서 설계"),
                            ("PLC_DESIGN", "PLC 설계"),
                            ("COMMUNICATION_DESIGN", "통신 설계"),
                            ("HMI_DESIGN", "HMI 설계"),
                            ("ALARM_INTERLOCK_DESIGN", "알람/인터록 설계"),
                            ("SEQUENCE_DESIGN", "시퀀스 설계"),
                            ("FAT_PLAN", "FAT 계획"),
                            ("SAT_PLAN", "SAT 계획"),
                            ("VENDOR_CODE_GENERATION", "벤더 코드 생성"),
                            ("AS_BUILT_RELEASE", "As-Built 릴리스"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성 중"),
                            ("IN_REVIEW", "검토 중"),
                            ("APPROVED", "승인됨"),
                            ("REJECTED", "거절됨"),
                            ("SUPERSEDED", "대체됨"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["target"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(max_length=12)),
                ("to_status", models.CharField(max_length=12)),
                ("reason", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="approvals.approval",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="approval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["DRAFT", "IN_REVIEW", "APPROVED"])),
                fields=("project", "target"),
                name="uniq_active_approval_per_target",
            ),
        ),
    ]
