# Generated by Django 5.2.15 on 2026-07-06 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "진행 중"),
                            ("COMPLETED", "완료"),
                            ("ABANDONED", "중단"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to="projects.project",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("text", models.TextField()),
                ("help_text", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPANY", "회사"),
                            ("INDUSTRY", "업종"),
                            ("PROCESS", "공정"),
                            ("PRODUCTION", "생산"),
                            ("DEVICE", "설비"),
                            ("MATERIAL", "물질"),
                            ("SENSOR", "센서"),
                            ("QUALITY", "품질"),
                            ("SAFETY", "안전"),
                            ("ENVIRONMENT", "환경"),
                            ("MAINTENANCE", "유지보수"),
                            ("NETWORK", "네트워크"),
                            ("COMMUNICATION", "통신"),
                            ("PLC", "PLC"),
                            ("HMI", "HMI"),
                            ("SCADA", "SCADA"),
                            ("HISTORIAN", "Historian"),
                            ("MES_ERP", "MES/ERP"),
                            ("ALARM", "알람"),
                            ("INTERLOCK", "인터록"),
                            ("SEQUENCE", "시퀀스"),
                            ("FAT", "FAT"),
                            ("SAT", "SAT"),
                            ("DELIVERY", "납품"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "텍스트"),
                            ("YES_NO", "예/아니오"),
                            ("SINGLE_CHOICE", "단일 선택"),
                            ("MULTI_CHOICE", "복수 선택"),
                            ("INTEGER", "정수"),
                            ("DECIMAL", "소수"),
                            ("RANGE", "범위"),
                            ("UNIT_VALUE", "단위값"),
                            ("DEVICE_LIST", "설비 목록"),
                            ("TABLE", "표"),
                            ("FILE_UPLOAD", "파일 업로드"),
                            ("CONFIRMATION", "확인"),
                        ],
                        max_length=20,
                    ),
                ),
                ("answer_schema", models.JSONField(blank=True, default=dict)),
                ("priority", models.IntegerField(default=0)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "치명적"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("required_conditions", models.JSONField(blank=True, default=dict)),
                ("exclusion_conditions", models.JSONField(blank=True, default=dict)),
                ("applicable_industries", models.JSONField(blank=True, default=list)),
                ("applicable_processes", models.JSONField(blank=True, default=list)),
                ("unlocks_facts", models.JSONField(blank=True, default=list)),
                ("unlocks_decisions", models.JSONField(blank=True, default=list)),
                ("risk_detection_tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"), name="uniq_question_code_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InterviewAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_answer", models.JSONField()),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="interview.interviewsession",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="interview.question",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="interview.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
