# Generated by Django 5.2.15 on 2026-07-06 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interview", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fact_key", models.CharField(max_length=255)),
                ("value_json", models.JSONField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("STRING", "문자열"),
                            ("NUMBER", "숫자"),
                            ("BOOLEAN", "불리언"),
                            ("LIST", "목록"),
                            ("OBJECT", "객체"),
                        ],
                        max_length=10,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ANSWER", "인터뷰 답변"),
                            ("RULE", "규칙 적용"),
                            ("LLM", "LLM 구조화"),
                            ("MANUAL", "수동 입력"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "제안됨"),
                            ("CONFIRMED", "확정됨"),
                            ("CONFLICTED", "충돌"),
                            ("SUPERSEDED", "대체됨"),
                            ("REJECTED", "거절됨"),
                        ],
                        default="PROPOSED",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="projects.project",
                    ),
                ),
                (
                    "source_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facts",
                        to="interview.interviewanswer",
                    ),
                ),
            ],
            options={
                "ordering": ["fact_key", "-version"],
                "indexes": [
                    models.Index(
                        fields=["project", "fact_key"],
                        name="requirement_project_da59f1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "fact_key", "version"),
                        name="uniq_fact_key_version",
                    )
                ],
            },
        ),
    ]
