# Generated by Django 5.2.15 on 2026-07-06 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[
                            ("INDUSTRY", "Industry Knowledge"),
                            ("PROCESS", "Process Knowledge"),
                            ("DEVICE", "Device Knowledge"),
                            ("SENSOR", "Instrument/Sensor Knowledge"),
                            ("CONTROL", "Control Knowledge"),
                            ("COMMUNICATION", "Communication Knowledge"),
                            ("HMI_SCADA", "HMI/SCADA Knowledge"),
                            ("FAT_SAT", "FAT/SAT Knowledge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("conditions_json", models.JSONField(blank=True, default=dict)),
                ("recommendations_json", models.JSONField(blank=True, default=list)),
                ("constraints_json", models.JSONField(blank=True, default=list)),
                ("references_json", models.JSONField(blank=True, default=list)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성 중"),
                            ("IN_REVIEW", "검토 중"),
                            ("APPROVED", "승인됨"),
                            ("REJECTED", "거절됨"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "version"), name="uniq_knowledge_code_version"
                    )
                ],
            },
        ),
    ]
