# Generated by Django 5.2.15 on 2026-07-07 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design", "0002_designdecision_generated_by_rule_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("condition", models.CharField(blank=True, max_length=255)),
                ("delay_seconds", models.FloatField(default=0)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음"),
                            ("MEDIUM", "보통"),
                            ("HIGH", "높음"),
                            ("CRITICAL", "치명적"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("operator_action", models.TextField(blank=True)),
                (
                    "reset_type",
                    models.CharField(
                        choices=[("AUTO", "자동 복귀"), ("MANUAL", "수동 복귀")],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                ("latching", models.BooleanField(default=False)),
                ("related_interlock", models.CharField(blank=True, max_length=50)),
                ("fat_test_required", models.BooleanField(default=True)),
                ("sat_test_required", models.BooleanField(default=True)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarms",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "code"), name="uniq_alarm_per_project"
                    )
                ],
            },
        ),
    ]
