# Generated by Django 5.2.15 on 2026-07-07 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design", "0002_designdecision_generated_by_rule_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IOPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag", models.CharField(max_length=100)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("DI", "디지털 입력"),
                            ("DO", "디지털 출력"),
                            ("AI", "아날로그 입력"),
                            ("AO", "아날로그 출력"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("source_type", models.CharField(blank=True, max_length=20)),
                ("source_ref", models.CharField(blank=True, max_length=100)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="io_points",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="io_points",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["signal_type", "tag"],
            },
        ),
    ]
