# Generated by Django 5.2.15 on 2026-07-07 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("io_points", "0001_initial"),
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iopoint",
            name="sensor_requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="io_points",
                to="sensors.sensorrequirement",
            ),
        ),
        migrations.AddConstraint(
            model_name="iopoint",
            constraint=models.UniqueConstraint(
                fields=("project", "tag"), name="uniq_io_tag_per_project"
            ),
        ),
    ]
