# Generated by Django 5.2.15 on 2026-07-07 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design", "0002_designdecision_generated_by_rule_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("measurement_type", models.CharField(max_length=50)),
                ("measurement_principle", models.CharField(blank=True, max_length=50)),
                ("sensor_technology", models.CharField(blank=True, max_length=100)),
                (
                    "signal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DI", "디지털 입력"),
                            ("DO", "디지털 출력"),
                            ("AI", "아날로그 입력"),
                            ("AO", "아날로그 출력"),
                        ],
                        max_length=10,
                    ),
                ),
                ("accuracy", models.CharField(blank=True, max_length=50)),
                ("range_text", models.CharField(blank=True, max_length=100)),
                ("response_time", models.CharField(blank=True, max_length=50)),
                (
                    "material_compatibility",
                    models.CharField(blank=True, max_length=200),
                ),
                ("environmental_rating", models.CharField(blank=True, max_length=50)),
                ("installation_constraints", models.TextField(blank=True)),
                ("maintenance_requirements", models.TextField(blank=True)),
                (
                    "communication_requirements",
                    models.CharField(blank=True, max_length=100),
                ),
                ("is_continuous", models.BooleanField(default=True)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sensor_requirements",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_requirements",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["measurement_type"],
            },
        ),
        migrations.CreateModel(
            name="SensorCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("rationale", models.TextField(blank=True)),
                ("rejected", models.BooleanField(default=False)),
                ("reject_reason", models.TextField(blank=True)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="sensors.sensorrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["rejected", "vendor"],
            },
        ),
        migrations.AddIndex(
            model_name="sensorrequirement",
            index=models.Index(
                fields=["project", "measurement_type"],
                name="sensors_sen_project_2f401e_idx",
            ),
        ),
    ]
