# Generated by Django 5.2.15 on 2026-07-07 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design", "0002_designdecision_generated_by_rule_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("PLC", "PLC"),
                            ("HMI", "HMI"),
                            ("REMOTE_IO", "Remote I/O"),
                            ("INVERTER", "인버터"),
                            ("SERVO", "서보"),
                            ("SCADA", "SCADA"),
                            ("GATEWAY", "게이트웨이"),
                            ("MES_ERP", "MES/ERP"),
                            ("METER", "계측기"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comm_nodes",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_nodes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["node_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="CommLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("protocol", models.CharField(max_length=50)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("CONTROL", "제어 네트워크(PLC-HMI)"),
                            ("FIELD", "필드 네트워크(Remote I/O/구동)"),
                            ("SUPERVISORY", "감시 네트워크(SCADA)"),
                            ("ENTERPRISE", "상위 연동(MES/ERP)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("medium", models.CharField(blank=True, max_length=50)),
                (
                    "failure_behavior",
                    models.CharField(
                        choices=[
                            ("HOLD", "마지막 값 유지"),
                            ("SAFE_STATE", "안전 상태로 전환"),
                            ("ALARM_ONLY", "알람만"),
                        ],
                        default="ALARM_ONLY",
                        max_length=20,
                    ),
                ),
                ("comm_alarm", models.BooleanField(default=True)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comm_links",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_links",
                        to="projects.project",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_out",
                        to="communications.commnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_in",
                        to="communications.commnode",
                    ),
                ),
            ],
            options={
                "ordering": ["segment"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requirement", models.CharField(max_length=50)),
                ("detail", models.CharField(blank=True, max_length=255)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_requirements",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_requirements",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["requirement"],
            },
        ),
    ]
