# Generated by Django 5.2.15 on 2026-07-07 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design", "0002_designdecision_generated_by_rule_and_more"),
        ("io_points", "0002_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HMIScreen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("purpose", models.CharField(blank=True, max_length=255)),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("OPERATOR", "운전자"),
                            ("SUPERVISOR", "관리자"),
                            ("ENGINEER", "엔지니어"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("OPERATOR", "운전자"),
                            ("SUPERVISOR", "관리자"),
                            ("ENGINEER", "엔지니어"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                ("required_tags", models.JSONField(blank=True, default=list)),
                ("commands", models.JSONField(blank=True, default=list)),
                ("status_objects", models.JSONField(blank=True, default=list)),
                ("alarm_objects", models.JSONField(blank=True, default=list)),
                ("trend_objects", models.JSONField(blank=True, default=list)),
                ("navigation", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hmi_screens",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmi_screens",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HMITag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("signal_type", models.CharField(blank=True, max_length=10)),
                (
                    "io_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hmi_tags",
                        to="io_points.iopoint",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="hmi_design.hmiscreen",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="hmiscreen",
            constraint=models.UniqueConstraint(
                fields=("project", "code"), name="uniq_hmi_screen_per_project"
            ),
        ),
    ]
