# Generated by Django 5.2.15 on 2026-07-07 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design", "0002_designdecision_generated_by_rule_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PLCSizingResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("di_count", models.PositiveIntegerField(default=0)),
                ("do_count", models.PositiveIntegerField(default=0)),
                ("ai_count", models.PositiveIntegerField(default=0)),
                ("ao_count", models.PositiveIntegerField(default=0)),
                ("spare_margin_percent", models.PositiveIntegerField(default=20)),
                ("factors_json", models.JSONField(blank=True, default=dict)),
                (
                    "required_class",
                    models.CharField(
                        choices=[
                            ("MICRO", "마이크로/블록형"),
                            ("COMPACT", "컴팩트형"),
                            ("MODULAR", "모듈형(중형)"),
                            ("HIGH_END", "고성능/이중화"),
                        ],
                        max_length=20,
                    ),
                ),
                ("minimum_spec_json", models.JSONField(blank=True, default=dict)),
                ("selection_reason", models.TextField(blank=True)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plc_sizing_results",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plc_sizing_results",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PLCCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vendor", models.CharField(max_length=100)),
                ("family", models.CharField(blank=True, max_length=100)),
                ("accepted", models.BooleanField(default=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "sizing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="plc_design.plcsizingresult",
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted", "vendor"],
            },
        ),
    ]
