# Generated by Django 5.2.15 on 2026-07-07 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("design", "0002_designdecision_generated_by_rule_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sequences",
                        to="design.designdecision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SequenceStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_no", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("entry_condition", models.CharField(blank=True, max_length=255)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("completion_condition", models.CharField(blank=True, max_length=255)),
                ("timeout_seconds", models.FloatField(blank=True, null=True)),
                ("timeout_alarm", models.CharField(blank=True, max_length=50)),
                ("abort_condition", models.CharField(blank=True, max_length=255)),
                ("hold_condition", models.CharField(blank=True, max_length=255)),
                ("resume_condition", models.CharField(blank=True, max_length=255)),
                ("next_step", models.PositiveIntegerField(blank=True, null=True)),
                ("fallback_step", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="sequences.sequence",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "step_no"],
            },
        ),
        migrations.AddConstraint(
            model_name="sequence",
            constraint=models.UniqueConstraint(
                fields=("project", "code"), name="uniq_sequence_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="sequencestep",
            constraint=models.UniqueConstraint(
                fields=("sequence", "step_no"), name="uniq_step_no_per_sequence"
            ),
        ),
    ]
